CREATE EXTENSION IF NOT EXISTS 'pgcrypto';

CREATE TABLE USUARIO(
    USU_ID UUID NOT NULL DEFAULT gen_random_uuid(),
    USU_EMAIL VARCHAR(100) NOT NULL,
    USU_NOME VARCHAR(100) NOT NULL,
    USU_SENHA VARCHAR(100) NOT NULL,
    USU_DATACRIACAO TIMESTAMP NOT NULL DEFAULT current_timestamp,
    USU_RECEBERALERTA BOOL NOT NULL DEFAULT FALSE,
);